facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
github: "https://github.com/glennpascal45"
linkedin: "https://www.linkedin.com/in/glenn-mouhingou/"
email: "pascal.mouhingou@gmail.com"
name: "Glenn Pascal Mouhingou"
location: Casablanca - Morocco
phone: (212) 708-00-50-29
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
