facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
github: "https://github.com/glennpascal45"
linkedin: "https://www.linkedin.com/in/glenn-mouhingou/"
email: "pascal.mouhingou@gmail.com"
name: "Glenn Pascal Mouhingou"
email: "contact@example.org"
name: "Glenn Pascal Mouhingou"
location: Casablanca
phone: (999) 999-9999
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
