color: "#4f46e5"
copyright: "Copyright &copy; 2024 Glenn Pascal Mouhingou. All Rights Reserved."
footer:
  - title: About
    content: >
      Glenn Pascal is an Industrial Engineer.


  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
style: blue
# logo: /image/logo.png
# logo_small: /image/logo.
about_us: >
  Glenn Pascal is an Industrial Engineer.
recent_posts:
  enable: true
