color: "#dc2626"
copyright: "Copyright &copy; 2024 Glenn Pascal Mouhingou. All Rights Reserved."
footer:
  - title: About
    content: >
        


  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Me
    contact: true
  - title: Important Links
    menu: true
style: blue
logo: /image/logo.png
logo_small: /image/logo.png
about_us: >
  
recent_posts:
  enable: true
